In [2]:
import torch

## Repo
김태희님의 Pytorch-A-to-Z

https://github.com/shwksl101/Pytorch-A-to-Z/blob/master/1_Pytorch_Basic/1_torch_package.ipynb

## 1. Create Tensor

In [2]:
# torch.rand(size)
# 0~1 사이의 연속균등분포에서 값을 뽑아 5X3텐서를 생성합니다. ~U(0,1)
x1 = torch.rand(2,3)
x1

tensor([[0.6893, 0.4169, 0.5150],
        [0.8809, 0.4304, 0.0429]])

In [3]:
# torch.randn(size)
# randn의 경우 평균은 0 표준편차는 1인 정규분포
x2 = torch.randn(2,3)
x2

tensor([[-0.0897, -1.3268, -0.4049],
        [-1.3461, -1.2552, -1.6468]])

In [4]:
# torch.randperm(n)
# 0 부터 n-1까지 1씩 늘어나며 값을 랜덤으로 정렬
x3 = torch.randperm(5)
x3

tensor([0, 3, 4, 2, 1])

#### 2)  empty, zeros, ones, arange, max

In [5]:
# torch.empty(size)
# 원하는 크기의 빈 텐서를 생성합니다
x1 = torch.empty(2,3)
x1

tensor([[4.2039e-45, 0.0000e+00, 1.4013e-45],
        [0.0000e+00, 1.4013e-45, 0.0000e+00]])

In [6]:
# torch.zeros(size)
# 원하는 크기의 빈 텐서를 생성합니다.
x2 = torch.zeros(2,3)
x2

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# torch.ones(size)
# 원하는 크기의 1의 값을 가진 텐서를 생성합니다.
x3 = torch.ones(2,3)
x3

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# torch.arange(start, end, step=1)
# start값부터 end값 전까지 step만큼 더하며 텐서를 생성합니다.
x4 = torch.arange(0,3,step=0.5)
x4

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])

In [10]:
# torch.max(input, dim keepdim=False, out = None) -> (Temsor, LongTensor)
# tensor의 최대값을 산출

x = torch.rand(2,3)
x

tensor([[0.1796, 0.2287, 0.6205],
        [0.4968, 0.3060, 0.6768]])

In [11]:
# 최대값을 출력
print(torch.max(x))

tensor(0.6768)


In [12]:
# 해당 차원에서 최대값과 그 위치를 출력 1은 행
print(torch.max(x,1))

(tensor([0.6205, 0.6768]), tensor([2, 2]))


In [13]:
# 해당 차원에서 최대값과 그 위치를 출력 1은 행 0은 열
print(torch.max(x,0))

(tensor([0.4968, 0.3060, 0.6768]), tensor([1, 1, 1]))


In [14]:
# 위치를 출력
print(torch.max(x,1)[1])

tensor([2, 2])


#### Tensor Data Type

In [16]:
# torch.empty(size, dtype = )
# torch.zeros(size, dtype = )
# torch.arange(start, end, dtype = )

# torch에서 지원하는 다양한 data type을 옵션으로 지정할 수 있습니다.
x = torch.empty(2,3,dtype = torch.float)
y = torch.zeros(2,3,dtype = torch.long)
z = torch.arange(0,3, step = 0.5, dtype = torch.double)

print(x)
print(y)
print(z)

tensor([[1.2358e+29, 4.5907e-41, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000], dtype=torch.float64)


In [17]:
# torch.tensor(size or list, dtype = torch.floattensor)
# 원하는 텐서를 바로 생성

x = torch.tensor([5,5,3])
x

tensor([5, 5, 3])

In [18]:
# torch.FloatTensor(size or list)
x = torch.FloatTensor(2,3)   # 형태로 들어간다. 
print(x)
x = torch.FloatTensor([2,3]) # list로 들어가면 값이 들어간다
print(x)

tensor([[0.0000e+00, 0.0000e+00, 2.8026e-45],
        [0.0000e+00, 1.4013e-45, 0.0000e+00]])
tensor([2., 3.])


In [4]:
# tensor.type_as(tensor_type)
# tensor 형 변환
x = torch.FloatTensor(2,3)  
print(x)
x = x.type_as(torch.IntTensor())
print(x)

tensor([[-1.5377e-27,  4.5907e-41,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)


#### 4) Tensor Size

In [20]:
# tensor.size()

x = torch.FloatTensor(10,12,3,3)
print(x.size()[:])
print(x.size()[0])

torch.Size([10, 12, 3, 3])
10


In [21]:
x = x.new_ones(5,3,dtype=torch.double) #5,3 차원의 새로운 텐서를 생성
print(x)

x = torch.randn_like(x, dtype=torch.float) # 같은 size에서 랜덤한 숫자로 채워진 텐서 생성
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.6832,  0.3435, -0.3797],
        [ 0.4882,  0.5732,  2.8060],
        [ 1.5622, -1.2373, -0.0996],
        [-1.2841,  0.0030, -0.6341],
        [-0.5604,  0.6939, -1.3111]])


## 2. Math Operations
#### 1) add, mul, div

In [22]:
# torch.add()
# 텐서의 값끼리 더합니다.

x1 = torch.FloatTensor([[1,2,3], [4,5,6]])
x2 = torch.FloatTensor([[1,2,3], [4,5,6]])
add = torch.add(x1,x2)
print(add)
print(x1 - x2)
print(x1 + x2)

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])


In [23]:
# 차원이 다르더라고 안쪽 차원만 같으면 연산이 가능하다
x = torch.rand(1,5,3)
y = torch.rand(5,3)
torch.add(x,y)

tensor([[[0.4290, 0.8858, 0.9586],
         [0.2309, 0.7601, 1.3780],
         [1.4721, 0.5172, 0.4473],
         [0.8552, 1.0722, 0.3748],
         [0.6519, 0.6478, 0.7560]]])

In [24]:
x

tensor([[[0.0421, 0.5418, 0.7683],
         [0.0398, 0.6646, 0.7982],
         [0.9641, 0.5097, 0.3195],
         [0.5429, 0.9056, 0.0196],
         [0.1151, 0.5825, 0.1404]]])

In [25]:
# torch.add 말고 add_의 경우에는 이러한 연산기능이 지원되지 않습니다. 따라서 먼저 x를 같은 차원으로 바꿔줍니다.
# x = torch.rand(1,5,3)
# y.add_(x)
# print(y)

x = torch.rand(5,3)
y.add_(x)
print(y)

tensor([[0.8675, 1.0479, 0.2082],
        [0.2763, 0.6110, 0.5812],
        [0.5950, 0.3535, 1.0084],
        [0.9479, 0.7773, 1.2356],
        [1.0021, 0.6699, 1.0680]])


In [26]:
# x 텐서의 2열을 불러옵니다. numpy 연산이 지원됩니다.
print(x)
print(x[:,1])

tensor([[0.4805, 0.7040, 0.0179],
        [0.0852, 0.5154, 0.0014],
        [0.0870, 0.3460, 0.8806],
        [0.6357, 0.6107, 0.8805],
        [0.4653, 0.6046, 0.4524]])
tensor([0.7040, 0.5154, 0.3460, 0.6107, 0.6046])


In [27]:
# torch.mul()
# hadamard product, mxn, mxn 행렬 2개를 곱합니다. 덧셈에 대해 분배법칙을 따릅니다.
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
x3 = torch.mul(x1,x2)
x4 = x1*x2

print(x3)
print(x4)

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])


In [28]:
# torch.mul()

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = x1*10
print(x1)
print(x2)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[10., 20., 30.],
        [40., 50., 60.]])


In [29]:
# torch.div()
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
x3 = torch.div(x1,x2)
x4 = x1 / x2
print(x3)
print(x4)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [30]:
# torch.div()

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x1 / 5 # 결국 같다.

tensor([[0.2000, 0.4000, 0.6000],
        [0.8000, 1.0000, 1.2000]])

#### 2) pow, exp, log

In [31]:
# torch.pow(input, exponent)

x1 = torch.rand(3,4)
print(x1)
print(torch.pow(x1,2),"\n",x1**2)

tensor([[0.5637, 0.1058, 0.8667, 0.4151],
        [0.4358, 0.6964, 0.3052, 0.3129],
        [0.0734, 0.5014, 0.1577, 0.1797]])
tensor([[0.3177, 0.0112, 0.7512, 0.1723],
        [0.1899, 0.4850, 0.0932, 0.0979],
        [0.0054, 0.2514, 0.0249, 0.0323]]) 
 tensor([[0.3177, 0.0112, 0.7512, 0.1723],
        [0.1899, 0.4850, 0.0932, 0.0979],
        [0.0054, 0.2514, 0.0249, 0.0323]])


In [32]:
# torch.exp(tensor, out=None)
x1 = torch.rand(3,4)
print(x1)
print(torch.exp(x1))

tensor([[0.3133, 0.0092, 0.5695, 0.8404],
        [0.6993, 0.8222, 0.4575, 0.3812],
        [0.6937, 0.9164, 0.6517, 0.4467]])
tensor([[1.3680, 1.0092, 1.7674, 2.3173],
        [2.0124, 2.2756, 1.5801, 1.4641],
        [2.0011, 2.5002, 1.9189, 1.5632]])


In [33]:
#torch.log(input, out = None)
x1 = torch.rand(3,4)
print(x1)
print(torch.log(x1))

tensor([[0.5101, 0.2915, 0.8707, 0.7827],
        [0.8654, 0.1915, 0.9409, 0.7767],
        [0.5130, 0.7184, 0.5237, 0.4971]])
tensor([[-0.6731, -1.2328, -0.1384, -0.2450],
        [-0.1446, -1.6530, -0.0609, -0.2528],
        [-0.6675, -0.3307, -0.6468, -0.6989]])


In [34]:
# torch.mm(matrix1, matrix2)
x1 = torch.rand(3,4)
x2 = torch.rand(4,5)
print(x1)
print(x2)
print(torch.mm(x1,x2))

tensor([[0.0852, 0.5292, 0.1017, 0.8863],
        [0.6338, 0.4934, 0.0171, 0.0892],
        [0.5980, 0.1779, 0.5409, 0.7208]])
tensor([[0.4007, 0.1224, 0.1138, 0.9392, 0.1185],
        [0.8995, 0.6039, 0.1684, 0.7706, 0.9113],
        [0.9233, 0.2095, 0.8952, 0.8474, 0.7715],
        [0.8385, 0.9128, 0.9417, 0.1951, 0.8261]])
tensor([[1.3471, 1.1604, 1.0244, 0.7469, 1.3029],
        [0.7884, 0.4606, 0.2545, 1.0074, 0.6116],
        [1.5034, 0.9519, 1.2609, 1.2977, 1.2457]])


In [35]:
# torch.bmm(batch_matrix1, batch_matrix2)
x1 = torch.rand(10,3,4)
x2 = torch.rand(10,4,5)

torch.bmm(x1,x2).size()

torch.Size([10, 3, 5])

## 벡터의 내적

In [119]:
torch.dot(torch.tensor([2,3]), torch.tensor([2,1])) # 2*2 + 3*1

tensor(7)

In [120]:
# torch.t (matrix)
# transpose

x1 = torch.rand(3,4)
print(x1.size(), x1.t().size())

torch.Size([3, 4]) torch.Size([4, 3])


In [121]:
x1 # 3X4

tensor([[0.4893, 0.8701, 0.6273, 0.4578],
        [0.7077, 0.7361, 0.8195, 0.0407],
        [0.1573, 0.5072, 0.0096, 0.9575]])

In [122]:
x1.t() #4X3

tensor([[0.4893, 0.7077, 0.1573],
        [0.8701, 0.7361, 0.5072],
        [0.6273, 0.8195, 0.0096],
        [0.4578, 0.0407, 0.9575]])

In [40]:
#torch.transpose(input, dim0, dim1)
x1 = torch.rand(10,3,4)
x1.size(), torch.transpose(x1,1,2).size(), x1.transpose(1,2).size()

(torch.Size([10, 3, 4]), torch.Size([10, 4, 3]), torch.Size([10, 4, 3]))

In [41]:
# torch.eig(a, eigenvectors=False)
# eigen_value, eigen_vector

x1 = torch.rand(2,2)
print(x1, "\n", torch.eig(x1, True))

tensor([[0.6425, 0.0654],
        [0.0683, 0.6790]]) 
 (tensor([[0.5914, 0.0000],
        [0.7300, 0.0000]]), tensor([[-0.7885, -0.5988],
        [ 0.6150, -0.8009]]))


## 3. Tensor to Numpy, Numpy to Tensor

In [5]:
import numpy as np
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [6]:
# tensor.numpy() tensor -> numpy
b = a.numpy()
print(b)


[1. 1. 1. 1. 1.]


In [7]:
# torch.from_numpy(ndarray) numpy -> tensor

a = np.ones(5)
b = torch.from_numpy(a)

print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


## 4. Indexing, Slicing, Joining
#### 1) Indexing

In [45]:
# tensor, index_select(input, dim, index)

x = torch.rand(4,3)

In [46]:
x

tensor([[0.6947, 0.7621, 0.1734],
        [0.0466, 0.1046, 0.7223],
        [0.7157, 0.2779, 0.8122],
        [0.8467, 0.5374, 0.3034]])

In [47]:
out = torch.index_select(x,0,torch.LongTensor([0,3])) # 0은 행

In [48]:
out

tensor([[0.6947, 0.7621, 0.1734],
        [0.8467, 0.5374, 0.3034]])

In [49]:
out2 = torch.index_select(x,1,torch.LongTensor([0,1])) # 1은 열

In [50]:
out2

tensor([[0.6947, 0.7621],
        [0.0466, 0.1046],
        [0.7157, 0.2779],
        [0.8467, 0.5374]])

In [51]:
print(x)

tensor([[0.6947, 0.7621, 0.1734],
        [0.0466, 0.1046, 0.7223],
        [0.7157, 0.2779, 0.8122],
        [0.8467, 0.5374, 0.3034]])


In [52]:
print(x[:,0])

tensor([0.6947, 0.0466, 0.7157, 0.8467])


In [53]:
print(x[0,:])

tensor([0.6947, 0.7621, 0.1734])


In [54]:
print(x[0:2,0:2])

tensor([[0.6947, 0.7621],
        [0.0466, 0.1046]])


In [55]:
#torch.masked_select(input, mask)
# 1로 표시한 텐서만 고릅니다
x = torch.randn(2,3)
mask = torch.ByteTensor([[0,0,1], [0,1,0]])
out = torch.masked_select(x, mask)

In [56]:
x

tensor([[ 1.6125,  0.8677, -0.5290],
        [ 1.9484, -0.7673, -0.4482]])

In [57]:
out

tensor([-0.5290, -0.7673])

#### 2) Joining

In [58]:
# torch.cat(seq, dim=0)
# dim을 기준으로 tensor를 합칩니다.

x = torch.FloatTensor([[1,2,3],
                       [4,5,6]])

y = torch.FloatTensor([[7,8,9],
                       [10,11,12]])

z1 = torch.cat([x,y], dim=0)
z2 = torch.cat([x,y], dim=1)
print(z1)
print(z2)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  7.,  8.,  9.],
        [ 4.,  5.,  6., 10., 11., 12.]])


In [59]:
# torch.stack(sequence, dim=0)
# dim을 기준으로 쌓습니다. 

x = torch.FloatTensor([1,2,3])
x_stack = torch.stack([x,x], dim=0)
x_stack2 = torch.stack([x,x], dim=1)
print(x_stack,"\n", x_stack2)

tensor([[1., 2., 3.],
        [1., 2., 3.]]) 
 tensor([[1., 1.],
        [2., 2.],
        [3., 3.]])


#### 3) Slicing

In [60]:
# torch.chunk(tensor, chunks, dim=0)
# tensor를 chunk단위로 쪼갭니다.

x = torch.FloatTensor([[1,2,3],
                       [4,5,6]])

y = torch.FloatTensor([[7,8,9],
                       [10,11,12]])

z1 = torch.cat([x,y], dim=0)

In [61]:
z1

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [62]:
x_1, x_2 = torch.chunk(z1,2,dim=0) # 행단위로 2개씩 자른다.

In [63]:
x_1

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [64]:
x_2

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [65]:
y_1, y_2, y_3 = torch.chunk(z1,3,dim=1)
y_1

tensor([[ 1.],
        [ 4.],
        [ 7.],
        [10.]])

In [66]:
y_2

tensor([[ 2.],
        [ 5.],
        [ 8.],
        [11.]])

In [67]:
y_3

tensor([[ 3.],
        [ 6.],
        [ 9.],
        [12.]])

In [68]:
# torch.split(tensor, split_size, dim = 0)
x = torch.FloatTensor([[1,2,3,4,5],
                       [4,5,6,7,8]])
y = torch.FloatTensor([[7,8,9,10,11],
                       [10,11,12,13,14]])
z1 = torch.cat([x,y],dim = 0)

In [69]:
z1

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 4.,  5.,  6.,  7.,  8.],
        [ 7.,  8.,  9., 10., 11.],
        [10., 11., 12., 13., 14.]])

In [70]:
x1, x2= torch.split(z1,2,dim=0)

In [71]:
x1

tensor([[1., 2., 3., 4., 5.],
        [4., 5., 6., 7., 8.]])

In [72]:
x2

tensor([[ 7.,  8.,  9., 10., 11.],
        [10., 11., 12., 13., 14.]])

In [73]:
y1,y2,y3 = torch.split(z1,2,dim=1) ## 2개씩 자른다

In [74]:
y1

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])

In [75]:
y2

tensor([[ 3.,  4.],
        [ 6.,  7.],
        [ 9., 10.],
        [12., 13.]])

In [76]:
y3

tensor([[ 5.],
        [ 8.],
        [11.],
        [14.]])

#### 4) squeezing

In [77]:
# torch.squeez(input, dim = None)
# 1짜리 차원을 줄입니다.
x1 = torch.FloatTensor(10,1,3,1,4)
x2 = torch.squeeze(x1)

In [78]:
x1.size(), x2.size()

(torch.Size([10, 1, 3, 1, 4]), torch.Size([10, 3, 4]))

In [79]:
# torch.unsqueeze(input, dim=None)
# 1짜리 차원을 더합니다
x1 = torch.FloatTensor(10,3,4)
x2 = torch.unsqueeze(x1,dim=0)

In [80]:
x1.size(), x2.size()

(torch.Size([10, 3, 4]), torch.Size([1, 10, 3, 4]))

## 5. Initialization

In [81]:
import torch.nn.init as init
x1 = init.uniform_(torch.FloatTensor(3,4), a=0, b=9)
x2 = init.normal_(torch.FloatTensor(3,4),mean=10, std=0.2)
x3 = init.constant_(torch.FloatTensor(3,4), 3.1415)

In [82]:
x1, x2, x3

(tensor([[8.3210, 5.7411, 1.1284, 6.8840],
         [5.0317, 7.7295, 3.6598, 7.2823],
         [1.8144, 0.4557, 5.2724, 3.7217]]),
 tensor([[10.3439, 10.0732, 10.3239, 10.4431],
         [10.1809,  9.8727, 10.3404,  9.8939],
         [10.1140,  9.8747,  9.8606, 10.0116]]),
 tensor([[3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415]]))

## 6. Math Operations

#### 1) Arithmatic operations

In [87]:
# torch.add()
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
add = torch.add(x1,x2)

print(x1), print(x2), print(add), print(x1+x2), print(x1-x2)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


(None, None, None, None, None)

In [88]:
# torch.add() broadcasting

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.add(x1,10)

print(x1)
print(x2)
print(x1+10)
print(x2-10)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[11., 12., 13.],
        [14., 15., 16.]])
tensor([[11., 12., 13.],
        [14., 15., 16.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [89]:
# torch.mul() -> size better match

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
x3 = torch.mul(x1,x2)

x3

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])

In [90]:
# torch.mul() -> broadcasting

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = x1*10

x2

tensor([[10., 20., 30.],
        [40., 50., 60.]])

In [91]:
# torch.div() -> size better match

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
x3 = torch.div(x1,x2)

x3

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [93]:
# torch.div() -> broadcasting

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])

x1/5

tensor([[0.2000, 0.4000, 0.6000],
        [0.8000, 1.0000, 1.2000]])

#### 2) Other Math Operations

In [97]:
# torch.pow(input, exponent)

x1 = torch.FloatTensor(3,4)
print(torch.pow(x1,2))
print(x1**2)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [98]:
# torch.exp(tensor, out = None)

x1 = torch.FloatTensor(3,4)
torch.exp(x1)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [99]:
# torch.log(inpt, out=None) -> natural logarithm

x1 = torch.FloatTensor(3,4)
torch.log(x1)

tensor([[-inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf]])

#### 3) Matrix operations

In [101]:
x1 = torch.FloatTensor(3,4)
x2 = torch.FloatTensor(4,5)

torch.mm(x1,x2)

tensor([[0., 0., 0., 0., nan],
        [0., 0., 0., 0., nan],
        [0., 0., 0., 0., nan]])

In [103]:
# torch.bmm(batch1, batch2) -> batch matrix multiplication

x1 = torch.FloatTensor(10,3,4)
x2 = torch.FloatTensor(10,4,5)

torch.bmm(x1,x2).size()

torch.Size([10, 3, 5])

In [113]:
# torch.dot(tensor1, tensor2) -> dot product of two tensor

x1 = torch.FloatTensor(4)
x2 = torch.FloatTensor(4)

torch.dot(x1,x2)

tensor(inf)

In [114]:
# torch.t(matrix) -> transposed matrix

x1 = torch.FloatTensor(3,4)
print(x1)
print(x1.t())

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [117]:
# torch.transpose(input, dim0, dim1) -> transposed matrix

x1 = torch.FloatTensor(10,3,4)
print(x1.size())
print(torch.transpose(x1,1,2).size())
print(x1.transpose(1,2).size())

torch.Size([10, 3, 4])
torch.Size([10, 4, 3])
torch.Size([10, 4, 3])
