## Variable & Automatic Gradient Calculation

- Tensor vs Variable
- Graph and Gradient 

## 1. Import Required Libraries

In [1]:
import torch
from torch.autograd import Variable

## 2. Tensor vs Variable

### 1) Declaration

In [2]:
x_tensor = torch.Tensor(3,4)
x_tensor
x_tensor.data # 원래는 Variable로 감싸진 형태만 data를 받았는데 tensor도 이제 받는듯..?

tensor([[1.3733e-14, 9.5680e+20, 7.2065e+31, 2.6301e+20],
        [1.4601e-19, 6.4069e+02, 4.3066e+21, 1.1824e+22],
        [4.3066e+21, 6.3828e+28, 3.8016e-39, 0.0000e+00]])

In [8]:
x_variable = Variable(x_tensor)
x_variable
x_variable.data

tensor([[1.3733e-14, 9.5680e+20, 7.2065e+31, 2.6301e+20],
        [1.4601e-19, 6.4069e+02, 4.3066e+21, 1.1824e+22],
        [4.3066e+21, 6.3828e+28, 3.8016e-39, 0.0000e+00]])

### 2) Variable of a Variable

In [9]:
# .data -> wrapped tensor
x_variable.data

tensor([[1.3733e-14, 9.5680e+20, 7.2065e+31, 2.6301e+20],
        [1.4601e-19, 6.4069e+02, 4.3066e+21, 1.1824e+22],
        [4.3066e+21, 6.3828e+28, 3.8016e-39, 0.0000e+00]])

In [10]:
print(x_variable.grad) # 연산진행 X 따라서 None이 출력

None


In [11]:
# .requires grad -> whether variable requires gradient

print(x_variable.requires_grad)                        # 처음에 안넣어줘서 False뜬다 
x_variable = Variable(x_tensor, requires_grad = True)  # 그래디언트 계산이 돼고 안돼고를 설정
x_variable.requires_grad

False


True

## 3. Graph & Variables

In [30]:
# create graph

x = Variable(torch.FloatTensor(3,4), requires_grad=True)
y = x**2 + 4*x
z = 2*y + 3

x.requires_grad, y.requires_grad, z.requires_grad # gradient계산여부 다 True

(True, True, True)

In [31]:
# .backward(gradient, retain_graph, create_graph, retain_variables) 백프로파게이션 자동으로
# compute gradient of current variable w.r.t. graph leaves

loss = torch.rand(3,4)
z.backward(loss)

print(x.grad)
y.grad, z.grad # 다 x로 이루어진 함수라 leaf node인 x에 대한 grad만 저장한다

tensor([[5.3395, 5.6302, 7.2208, 3.5229],
        [4.7059, 0.2659, 7.7184, 2.7003],
        [2.3630, 3.7341, 1.2561, 6.6380]])


(None, None)

In [28]:
loss = torch.rand(3,4)