## 1. Import Required Libraries

In [20]:
import torch
import torch.nn as nn
from torch.autograd import Variable
import torch.optim as optim
import torch.nn.init as init

## 2. Model & Optimizer

In [6]:
# 일반적으로 python의 class를 이용해 모델을 구현합니다.
# 일반적으로 __init__, forward, predict 등으로 이루어져 있습니다.

class SimpleLinearRegression(nn.Module):
    def __init__(self):
        super(SimpleLinearRegression, self).__init__()
        self.Layer = nn.Linear(1,1) # feature가 1이고 output 역시 1개이기 때문에 (1,1)
        
    # feed forward
    def forward(self,inputs):
        x = self.Layer(inputs)
        return x
    
    def predict(self, test_input):
        x = self.Layer(test_input)
        return x
    
model = SimpleLinearRegression() # 객체 설정
criterion = nn.MSELoss() # regression의 loss function은 MSE

# gradient descent로 w, b를 찾고 optimizer는 stochastic descent사용
# momentum은 관성을 추가하는 내용. 학습속도를 위해 추가

optimizer = optim.SGD(model.parameters(), lr = 0.01, momentum = 0.9)

## 3. Train


In [ ]:
for i in range(1000):
    
    # y = 2x + 0.1
    # input 은 일정하게 1.0, 2.0, 3.0이 들어가고 target은 2.1, 4.1, 6.1입니다.
    # 우리가 원하는 것은 w,b가 1000번의 학습을 통해 2와 0.1이 되는 것
    
    inputs = torch.Tensor([1.0, 2.0, 3.0]).unsqueeze(1)
    targets = torch.Tensor([2.1, 4.1, 6.1]).unsqueeze(1)
    
    model.zero_grad()
    y_pred = model(inputs)
    
    loss = criterion(y_pred, targets)
    loss.backward()
    
    # 계산된 gradient를 기반으로 optimizer를 이용해 w와 b를 update
    optimizer.step()
    
    if i % 200 ==0:
        print(loss)

## 4. Check Trained Parameters

In [9]:
# 1000 번 학스한 결과 w는 2, b는 0.1
w = list(model.parameters())
print(w)

[Parameter containing:
tensor([[2.0000]], requires_grad=True), Parameter containing:
tensor([0.1000], requires_grad=True)]


In [10]:
model.predict(torch.Tensor([10.0]))

tensor([20.1000], grad_fn=<AddBackward0>)

## Non lineart Data에 Linear Model을 적용

In [18]:
num_data = 1000
num_epoch = 1000

noise = init.normal(torch.FloatTensor(num_data,1), std=1)
x = init.uniform(torch.Tensor(num_data,1),-10,10)
y = 2*x +3
y_noise = 2**x + 3*x -2 + noise # y = 2x^2 + 3x -2 (Non_linear_data)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  after removing the cwd from sys.path.
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  """


In [19]:
for i in range(1000):

    
    model.zero_grad()
    y_pred = model(Variable(x))
    
    loss = criterion(y_pred, y_noise)
    loss.backward()
    
    # 계산된 gradient를 기반으로 optimizer를 이용해 w와 b를 update
    optimizer.step()
    
    if i % 200 ==0:
        print(loss) # loss가 줄어들지 않는다. 

tensor(37731.6055, grad_fn=<MseLossBackward>)
tensor(19849.1641, grad_fn=<MseLossBackward>)
tensor(19849.1641, grad_fn=<MseLossBackward>)
tensor(19849.1641, grad_fn=<MseLossBackward>)
tensor(19849.1641, grad_fn=<MseLossBackward>)
